# Stub project.yaml

# The following does practically nothing. It is present simply so that msfl
# automated builds run but don't fail until a real project.yaml is set up. The
# following should be deleted when this file is filled out with real data.
null_target:
  build_plan: validate_only
  output_filename: fake_font.ttf

    
# roman:
#   base: _common
#   sources:
#     designspace: Source/ufo-roman/SitkaVF/DesignSpace-UFO/Sitka VF.designspace
#     vtt: Source/vtt/SitkaVF-VTT.ttf
#   output_filename: SitkaVF.ttf
#   tables:
#     name:
#       4: Sitka Text
#       6: SitkaText
#     STAT:
#       axes:
#         - tag: ital
#           name: Italic
#           values:
#             - name: Regular
#               value: 0
#               flags: 0x2
#   regression:
#     known_errors:
#       - Tests/known_err_roman.yaml

# italic:
#   base: _common
#   sources:
#     designspace: Source/ufo-italic/SitkaVF/DesignSpace-UFO/Sitka VF Italic.designspace
#     vtt: Source/vtt/SitkaVF-Italic-VTT.ttf
#   output_filename: SitkaVF-Italic.ttf
#   tables:
#     name:
#       4: Sitka Text Italic
#       6: SitkaTextItalic
#     STAT:
#       axes:
#         - tag: ital
#           name: Italic
#           values:
#             - name: Italic
#               value: 1

# _common:
#   build_plan: designspace_to_variable_font
#   project_name: sitka
#   font_version: 2.01
#   build_options:
#     reverse_direction: no
#   tables:
#     head:
#       fontRevision: "{font_version}"
#       lowestRecPPEM: 9 # https://mstypography.visualstudio.com/SitkaVF/_workitems/edit/464
#     maxp:
#       maxStackElements: 634
#       maxSizeOfInstructions: 3957
#       maxStorage: 47
#       maxInstructionDefs: 1
#     meta:
#       dlng: Latn, Cyrl, Grek
#       slng: Latn, Cyrl, Grek
#       bild: "{toolchain_versions}; project git revision: {git_revision}"
#     name:
#       0: © 2021 Microsoft Corporation. All Rights Reserved.
#       1: Sitka Text
#       5: "Version {font_version}"
#       16: Sitka
#     OS/2:
#       achVendID: "MS  "
#     STAT:
#       axes:
#         - tag: opsz
#           name: Optical Size
#           values:
#             - name: Small
#               rangeMinValue: 0
#               nominalValue: 8
#               rangeMaxValue: 9.7
#             - name: Text
#               rangeMinValue: 9.7
#               nominalValue: 11
#               rangeMaxValue: 13.5
#             - name: Subheading
#               rangeMinValue: 13.5
#               nominalValue: 16.7391
#               rangeMaxValue: 18.5
#             - name: Heading
#               rangeMinValue: 18.5
#               nominalValue: 21.04336
#               rangeMaxValue: 23.5
#             # The following uses 27.49998 for max to avoid ambiguity of
#             # Display.max==Banner.min==Banner.nominal==Banner named instance coord
#             - name: Display
#               rangeMinValue: 23.5
#               nominalValue: 24.63033
#               rangeMaxValue: 27.49998
#             - name: Banner
#               rangeMinValue: 27.5
#               nominalValue: 27.5
#         - tag: wght
#           name: Weight
#           values:
#             - name: Regular
#               value: 400
#               flags: 0x2
#             - name: Semibold
#               value: 600
#             - name: Bold
#               value: 700
#   action_scripts:
#     - Source/fixup_cpsp.py
#   actions:
#     - name: sync_name_records
#     - name: fixup_cpsp
#   validation:
#     profile_modules:
#       - fontbakery.profiles.universal
#       - msfontlib.checks
#     exclude:
#       - com.google.fonts/check/dsig
#       - com.google.fonts/check/os2_metrics_match_hhea
#       - com.google.fonts/check/ftxvalidator_is_available
#       - com.google.fonts/check/family/win_ascent_and_descent # Must be consistent with existing versions
#       - com.google.fonts/check/unwanted_tables # We want MVAR
#       - com.google.fonts/check/unitsperem # We deliberately use non-power-of-2 UPM
#       - com.google.fonts/check/family/underline_thickness # Sitka was designed differently than David Lemon recommends
#       - com.google.fonts/check/fontbakery_version
#     include:
#       - msfontlib.checks_optional::com.microsoft/check/office_ribz
#   regression:
#     known_errors:
#       - Tests/known_err.yaml
#     gpos_tests:
#       - Tests/tests_gpos.txt
#     gsub_tests:
#       - Tests/tests_gsub.txt
#     render_tests:
#       - ppem: 100
#         tolerance: 5
#         hinting: True
