# Stub project.yaml

# The following does practically nothing. It is present simply so that msfl
# automated builds run but don't fail until a real project.yaml is set up. The
# following should be deleted when this file is filled out with real data.
null_target:
  build_plan: validate_only
  output_filename: fake_font.ttf

    
