trigger:
  batch: true # Batch multiple commits to the same branch into a single invocation
  branches:
    include:
      - main
      - work/*
  tags:
    include:
      - v*
  paths:
    exclude:
      - Artifacts

strategy:
  matrix:
    Linux_Python38:
      imageName: 'ubuntu-latest'
      python.version: '3.8'

pool:
  vmImage: $(imageName)

# Enable debug mode
# variables:
#   System.Debug: true

resources:
  repositories:
    - repository: ado-scripts
      name: MSFontTools/ado-scripts
      type: git
      ref: main #branch name

steps:
  - template: font-pipelines/font-build-test-publish.yaml@ado-scripts
    parameters:
      use_standalone: true
      regress: false
      validate: false
      save_build_artifacts: false # Turn this back on when we actually have a font to build
